module.exports = {
  dev: {
    "default-src": [
      "'self'",
      "http://localhost:3000",
      "https://d2kjgv54rdwtye.cloudfront.net",
      "https://p277xj9nqf.execute-api.ap-south-1.amazonaws.com",
      "https://ebrochure-nonprod-assets.s3.ap-south-1.amazonaws.com",
      "https://www.youtube.com",
    ],
    "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
    "script-src": [
      "'self'",
      "'unsafe-eval'",
      "blob:",
      "https://cdn.jsdelivr.net",
      "https://www.youtube.com",
      "https://cdnjs.cloudflare.com",
      "https://cdnjs.com",
      "https://cdn.dwolla.com",
    ],
    "img-src": [
      "'self'",
      "data:",
      "blob:",
      "http://localhost:3000",
      "https://d2kjgv54rdwtye.cloudfront.net",
    ],
    "media-src": [
      "'self'",
      "data:",
      "blob:",
      "http://localhost:3000",
      "https://d2kjgv54rdwtye.cloudfront.net",
    ],
    "font-src": ["'self'", "https://fonts.gstatic.com"],
    "connect-src": [
      "'self'",
      "blob:",
      "ws:",
      "https://d2kjgv54rdwtye.cloudfront.net",
      "https://p277xj9nqf.execute-api.ap-south-1.amazonaws.com",
      "https://cognito-idp.ap-south-1.amazonaws.com/",
      "https://ebrochure-nonprod-assets.s3.ap-south-1.amazonaws.com",
      "https://rrxd95yu1g.execute-api.ap-south-1.amazonaws.com",
    ],
  },
  uat: {
    "default-src": [
      "'self'",
      "http://localhost:3000",
      "https://d2kjgv54rdwtye.cloudfront.net",
      "https://p277xj9nqf.execute-api.ap-south-1.amazonaws.com",
      "https://ebrochure-nonprod-assets.s3.ap-south-1.amazonaws.com",
      "https://www.youtube.com",
    ],
    "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
    "script-src": [
      "'self'",
      "'unsafe-eval'",
      "blob:",
      "https://cdn.jsdelivr.net",
      "https://www.youtube.com",
      "https://cdnjs.cloudflare.com",
      "https://cdnjs.com",
      "https://cdn.dwolla.com",
    ],
    "img-src": [
      "'self'",
      "data:",
      "blob:",
      "http://localhost:3000",
      "https://d2kjgv54rdwtye.cloudfront.net",
    ],
    "media-src": [
      "'self'",
      "data:",
      "blob:",
      "http://localhost:3000",
      "https://d2kjgv54rdwtye.cloudfront.net",
    ],
    "font-src": ["'self'", "https://fonts.gstatic.com"],
    "connect-src": [
      "'self'",
      "blob:",
      "ws:",
      "https://d2kjgv54rdwtye.cloudfront.net",
      "https://p277xj9nqf.execute-api.ap-south-1.amazonaws.com",
      "https://cognito-idp.ap-south-1.amazonaws.com/",
      "https://ebrochure-nonprod-assets.s3.ap-south-1.amazonaws.com",
      "https://rrxd95yu1g.execute-api.ap-south-1.amazonaws.com",
    ],
  },
  prod: {
    "default-src": [
      "'self'",
      "https://d27xnkynewnw7.cloudfront.net",
      "https://rrxd95yu1g.execute-api.ap-south-1.amazonaws.com",
      "https://ebrochure-prod-assets.s3.ap-south-1.amazonaws.com",
      "https://www.youtube.com",
    ],
    "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
    "script-src": [
      "'self'",
      "blob:",
      "'unsafe-inline'",
      "'unsafe-eval'",
      "https://cdn.jsdelivr.net",
      "https://www.youtube.com",
      "https://cdnjs.cloudflare.com",
      "https://cdnjs.com",
      "https://cdn.dwolla.com",
    ],
    "img-src": [
      "'self'",
      "data:",
      "blob:",
      "https://d27xnkynewnw7.cloudfront.net",
    ],
    "media-src": [
      "'self'",
      "data:",
      "blob:",
      "https://d27xnkynewnw7.cloudfront.net",
    ],
    "font-src": ["'self'", "https://fonts.gstatic.com"],
    "connect-src": [
      "'self'",
      "blob:",
      "ws:",
      "https://d27xnkynewnw7.cloudfront.net",
      "https://cognito-idp.ap-south-1.amazonaws.com/",
      "https://rrxd95yu1g.execute-api.ap-south-1.amazonaws.com",
      "https://ebrochure-prod-assets.s3.ap-south-1.amazonaws.com",
    ],
  },
};
