import { ENV_VARIABLE } from "../variable";

const ENVIRONMENT = ENV_VARIABLE[process.env.REACT_APP_ENV];

export default {
  REGION: ENVIRONMENT?.AWS_CONFIG?.REGION,
  USER_POOL_ID: ENVIRONMENT?.AWS_CONFIG?.USER_POOL_ID,
  APP_CLIENT_ID: ENVIRONMENT?.AWS_CONFIG?.APP_CLIENT_ID,
  S3_BASE_URL: ENVIRONMENT?.AWS_CONFIG?.S3_BASE_URL,
};
